from enum import Enum

class ConversationState(Enum):
    INIT="INIT"
    COLLECTING_SYMPTOMS="COLLECTING_SYMPTOMS"
    SPECIALITY_INFERRED="SPECIALITY_INFERRED"
    SELECTING_DOCTOR="SELECTING_DOCTOR"
    CHECKING_AVAILABILITY="CHECKING_AVAILABILITY"
    COLLECTING_PATIENT_DETAILS="COLLECTING_PATIENT_DETAILS"
    END="END"


    
    # VALID_TRANSITIONS = {
    #"INIT": ["COLLECTING_SYMPTOMS"],
    #"COLLECTING_SYMPTOMS": ["SELECTING_DOCTOR"],
    #"SELECTING_DOCTOR": ["CHECKING_AVAILABILITY"],
    #"CHECKING_AVAILABILITY": ["COLLECTING_PATIENT_DETAILS"],
    #"COLLECTING_PATIENT_DETAILS": ["BOOKED"],
    #}
